name: build, export and deploy

on: push

# secrets.ssh_config example:
#   Host pastleo_me_host
#     HostName x.x.x.x
#     User xxx
#
# secrets.ssh_id_rsa should be filled with ssh private key content
# secrets.ssh_known_hosts should be filled with key fingerprint of deploy target host

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run lint

  build_export:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.2.0
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run build
    - run: npm run export
    - name: upload exported build
      uses: actions/upload-artifact@v1
      with:
        name: out
        path: out

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build_export
    runs-on: ubuntu-latest

    steps:
    - name: download exported build
      uses: actions/download-artifact@v1
      with:
        name: out
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gsutil -m rsync -r out/ "gs://${GCP_BUCKET_NAME}/"
      env:
        GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
